import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { GetServerSideProps } from "next";
import styles from "../styles/Home.module.css";
import path from "path";
import fs from "fs/promises";
import matter from "gray-matter";
import Link from "next/link";

const Home: NextPage = ({ articles }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Menu</h1>
        {/* <pre>{JSON.stringify(articles, null, 2)}</pre> */}
        <ul>{articles.map((article:any) => {
          return <li key={article.slug}>
            <Link href={`/blog/${article.slug}`} >
              <a>{article.title}</a>
            </Link>
            </li>
        })}</ul>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const blogDir = path.join(process.cwd(), "content/blog");
  const articles = await fs.readdir(blogDir);
  const contents = await Promise.all(
    articles.map(async (fileName) => {
      const filepath = path.join(blogDir, fileName);
      const buffer = await fs.readFile(filepath);
      const { data } = matter(buffer);
      return data;
    })
  );

  return {
    props: {
      articles: contents,
    },
  };
};
export default Home;
